version: "3.8"
services:
  wg-easy:
    environment:
      - WG_HOST=14.236.0.6
      - PASSWORD_HASH=$$2a$$12$$Bus55u4pTwtJ132fEwTT8u9qBS/bdsnOxC.5I73lHVoLhPTYQXSee
      - WG_PORT=51820
      - WG_DEFAULT_ADDRESS=10.9.0.x
      - WG_DEFAULT_DNS=1.1.1.1
      - WG_MTU=1420
    image: ghcr.io/wg-easy/wg-easy
    container_name: wg-easy-hp
    volumes:
      - /opt/wg-easy-hp:/etc/wireguard
    ports:
      - "51820:51820/udp"
      - "51821:51821/tcp"
    restart: unless-stopped
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    sysctls:
      - net.ipv4.ip_forward=1
      - net.ipv4.conf.all.src_valid_mark=1
