[Interface]
PrivateKey = EFE9iZ3n3l9s3deLvTGCCJYFIBO/7EJUz50mu4bgi0Q=
Address = 10.8.0.8/32
# Không dùng DNS của Pi để HP vẫn vào được internet bình thường
# DNS = 1.1.1.1

[Peer]
PublicKey = /9hFV69KBLquNVEtRzeUDpgUmK43KrwkEuTJq39IRgY=
PresharedKey = 825BrZaJ13XTFM7ok+oaOAmfd1r9jZQut4GBnS/Fdh0=
Endpoint = vungvang.duckdns.org:51820
# Chỉ định tuyến dải mạng 10.8.0.x qua VPN, toàn bộ net khác vẫn giữ nguyên
AllowedIPs = 10.8.0.0/24
PersistentKeepalive = 25
